### ISSUE TITLE
yo look in chat on fng 

### ISSUE THREAD

**Issue by ChillerDragon** [PathosEthosLogos/Leave-a-message-beep#1]
![screenshot_2023-06-27_18-50-13](https://github.com/PathosEthosLogos/Leave-a-message-beep/assets/20344300/3082da80-ae0d-4192-b0e5-e14d8f08b788)
![screenshot_2023-06-27_18-50-26](https://github.com/PathosEthosLogos/Leave-a-message-beep/assets/20344300/142acb8d-04ba-4f47-9b7d-bead8857ec28)

**Comment by PathosEthosLogos** [comment]
@ChillerDragon Haha sorry to get back to you so late

I generally have chat, broadcast, names, etc. off when playing FNG.

**Comment by ChillerDragon** [comment]
Rude!

Woah you are alive. Hello c:

Are you the same Pathos that sometimes posts in ddnet #developer?
